import { Mission, StrayCat, Guardian, TestimonialStory, Step, Post } from './types';

export const STEPS: Step[] = [
  {
    id: 1,
    title: 'Spot a cat',
    description: 'See a stray in need of care in your local neighborhood.',
    iconName: 'Eye',
  },
  {
    id: 2,
    title: 'Upload photo',
    description: 'Share a photo and precise geo-location via our app.',
    iconName: 'Camera',
  },
  {
    id: 3,
    title: 'Local Alert',
    description: 'Nearby volunteers receive an instant notification.',
    iconName: 'Bell',
  },
  {
    id: 4,
    title: 'Expert Care',
    description: 'The cat receives medical aid, food, and fostering.',
    iconName: 'HeartPulse',
  },
];

export const MISSIONS: Mission[] = [
  {
    id: 'mission-1',
    title: 'Refill Colony #42',
    type: 'feeding',
    distance: '2.4km',
    description: 'Colony #42 is running low on dry kibble and fresh water. 15 cats rely on this station daily.',
    urgent: true,
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=500',
    status: 'open',
  },
  {
    id: 'mission-2',
    title: 'Vet Transport',
    type: 'transport',
    distance: '5.1km',
    description: "Need transport for 'Mochi' from foster home to Eastside Clinic for urgent vaccination.",
    image: 'https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?auto=format&fit=crop&q=80&w=500',
    status: 'open',
  },
  {
    id: 'mission-3',
    title: 'Emergency Foster',
    type: 'foster',
    distance: '3.8km',
    description: 'Newly rescued kitten needs a safe indoor space for 48 hours while shelter space is prepped.',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1574158622643-69d34d72650a?auto=format&fit=crop&q=80&w=500',
    status: 'open',
  },
];

export const GUARDIANS: Guardian[] = [
  {
    id: 'guardian-1',
    name: 'John D.',
    title: 'CAT SAVIOR',
    exp: '24k XP',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=200',
    streak: 45,
    level: 'Expert Rescuer',
  },
  {
    id: 'guardian-2',
    name: 'Emma W.',
    title: 'FOOD GUARDIAN',
    exp: '18k XP',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    streak: 32,
    level: 'Community Feeder',
  },
  {
    id: 'guardian-3',
    name: 'Lara Croft',
    title: 'URBAN SCOUT',
    exp: '12k XP',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=200',
    streak: 19,
    level: 'Colony Spotter',
  },
];

export const TESTIMONIALS: TestimonialStory[] = [
  {
    id: 'story-1',
    catName: 'Oscar',
    author: 'Sarah Mitchell',
    role: 'VERIFIED ADOPTER',
    quote: '"From the cold streets to a warm bed, every journey is precious."',
    beforeImage: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&q=80&w=500',
    afterImage: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=500',
    details: "Oscar was found in a rain-soaked box on 5th Ave. Today, thanks to our volunteers, he's the king of a loving home in the suburbs.",
    location: 'Brooklyn, NY',
  },
  {
    id: 'story-2',
    catName: 'Milo',
    author: 'David Chen',
    role: 'FOSTER PARENT',
    quote: '"Seeing Milo transition from frightened to playful was pure magic."',
    beforeImage: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&q=80&w=500',
    afterImage: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&q=80&w=500',
    details: 'Milo was found trapped behind an industrial dumpster with an injured paw. After three weeks of dedicated care and a vet visit, his cheerful spirit completely bloomed.',
    location: 'Seattle, WA',
  },
  {
    id: 'story-3',
    catName: 'Luna',
    author: 'Elena Rostova',
    role: 'SHELTER MANAGER',
    quote: '"Luna showed us that love and warm patience can heal any scar."',
    beforeImage: 'https://images.unsplash.com/photo-1501820488136-72669149e0d4?auto=format&fit=crop&q=80&w=500',
    afterImage: 'https://images.unsplash.com/photo-1526336028075-9d5a0a9c7433?auto=format&fit=crop&q=80&w=500',
    details: 'Luna had spent nearly a year in our feral colony, too terrified of humans to approach. Slowly, using specialized feeding schedules, she built trust and is now happily snoring on a velvet couch.',
    location: 'Boston, MA',
  },
];

export const ADOPTABLE_CATS: StrayCat[] = [
  {
    id: 'cat-1',
    name: 'Whiskers',
    age: '5 months',
    breed: 'Tabby Kitten',
    gender: 'Male',
    status: 'Stable',
    image: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&q=80&w=500',
    description: 'Whiskers is incredibly energetic and loves toys with bells. He gets along beautifully with dogs and other cats.',
    location: 'Downtown Shelter',
    reportedAt: '2 days ago',
    tags: ['Playful', 'Lap Cat', 'Vaccinated'],
  },
  {
    id: 'cat-2',
    name: 'Mochi',
    age: '2 months',
    breed: 'Calico',
    gender: 'Female',
    status: 'Urgent',
    image: 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&q=80&w=500',
    description: 'Mochi is a tiny calico kitten recovering from a light cold. She is extremely vocal when she wants treats!',
    location: 'Eastside Foster',
    reportedAt: 'Today',
    tags: ['Affectionate', 'Needs Foster', 'Vocal'],
  },
  {
    id: 'cat-3',
    name: 'Barnaby',
    age: '2 years',
    breed: 'Domestic Shorthair',
    gender: 'Male',
    status: 'Stable',
    image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&q=80&w=500',
    description: 'Barnaby is a gentle giant who spent his first two years in an industrial park. He is very calm, quiet, and loves scratching posts.',
    location: 'Westside Haven',
    reportedAt: '1 week ago',
    tags: ['Calm', 'Independent', 'House trained'],
  },
  {
    id: 'cat-4',
    name: 'Cookie',
    age: '1 year',
    breed: 'Tuxedo Cat',
    gender: 'Female',
    status: 'Stable',
    image: 'https://images.unsplash.com/photo-1511044568932-338cba0ad803?auto=format&fit=crop&q=80&w=500',
    description: 'Cookie is a sweet tuxedo cat who was found in a subway station. She is incredibly purry and is always seeking head rubs.',
    location: 'Central Cattery',
    reportedAt: '4 days ago',
    tags: ['Friendly', 'Snuggler', 'Microchipped'],
  },
  {
    id: 'cat-5',
    name: 'Oliver',
    age: '3 years',
    breed: 'Maine Coon Mix',
    gender: 'Male',
    status: 'Fostered',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=500',
    description: 'Oliver is a large, fluffy gentle giant. He has a soft voice and loves sitting by the window watching birds.',
    location: 'Westside Foster',
    reportedAt: '3 days ago',
    tags: ['Fluffy', 'Gentle', 'Talkative'],
  },
  {
    id: 'cat-6',
    name: 'Ginger',
    age: '4 months',
    breed: 'Orange Tabby',
    gender: 'Male',
    status: 'Stable',
    image: 'https://images.unsplash.com/photo-1574158622643-69d34d72650a?auto=format&fit=crop&q=80&w=500',
    description: 'Ginger is extremely playful and is always chasing laser pointers. He loves cuddles once he is tired.',
    location: 'Central Cattery',
    reportedAt: '5 days ago',
    tags: ['Cuddly', 'Playful', 'Indoor'],
  },
  {
    id: 'cat-7',
    name: 'Simba',
    age: '1.5 years',
    breed: 'Abyssinian Mix',
    gender: 'Male',
    status: 'Urgent',
    image: 'https://images.unsplash.com/photo-1513360309081-36f20c385325?auto=format&fit=crop&q=80&w=500',
    description: 'Simba is an active boy who loves to jump on high shelves. He is neutered, vaccinated, and looking for an active home.',
    location: 'Eastside Foster',
    reportedAt: 'Yesterday',
    tags: ['Sassy', 'Hunter', 'Neutered'],
  },
  {
    id: 'cat-8',
    name: 'Cleo',
    age: '8 months',
    breed: 'Siamese',
    gender: 'Female',
    status: 'Fostered',
    image: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80&w=500',
    description: 'Cleo is a stunning Siamese with ocean blue eyes. She is highly intelligent and responds when you call her name.',
    location: 'Northside Sanctuary',
    reportedAt: '1 week ago',
    tags: ['Vocal', 'Smart', 'Elegant'],
  },
  {
    id: 'cat-9',
    name: 'Shadow',
    age: '2 years',
    breed: 'Bombay Cat',
    gender: 'Male',
    status: 'Stable',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=500',
    description: 'Shadow has a sleek, shiny jet-black coat. He is very quiet, loves warm spots, and takes a few days to warm up to new people.',
    location: 'Central Cattery',
    reportedAt: '6 days ago',
    tags: ['Quiet', 'Microchipped', 'Sleepy'],
  },
  {
    id: 'cat-10',
    name: 'Peanut',
    age: '3 months',
    breed: 'Domestic Shorthair',
    gender: 'Female',
    status: 'Stable',
    image: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&q=80&w=500',
    description: 'Peanut is a tiny sweetheart who is extremely energetic. She loves to sit on laps and purr during movie nights.',
    location: 'Downtown Shelter',
    reportedAt: 'Just Now',
    tags: ['Teeny-tiny', 'Energetic', 'Lap Cat'],
  }
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-1',
    author: {
      name: 'Sara Jenkins',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
      title: 'Maple Street Sanctuary',
      time: '4h ago'
    },
    title: 'The Journey Home: From the rain to the fireplace.',
    content: "Meet Oliver. Six weeks ago, he was found shivering in a damp box during a storm. Today, he's the king of his new forever home. Thank you everyone for the support!",
    isSuccessStory: true,
    beforeAfter: {
      beforeImg: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=400',
      afterImg: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&q=80&w=400',
      beforeLabel: 'BEFORE: LIFE ON THE STREETS',
      afterLabel: 'AFTER: HOME & HEALTH'
    },
    likes: 1240,
    commentsCount: 84,
    isLiked: false,
    isBookmarked: false,
    comments: [
      {
        author: 'Mark T.',
        text: 'This is why we do what we do! Beautiful transformation. ❤️',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150'
      }
    ],
    tags: ['Success Story', 'Adopted'],
    reactions: { '❤️': 82, '🎉': 45, '🙌': 31 }
  },
  {
    id: 'post-2',
    author: {
      name: 'Dr. Sarah Chen',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=150',
      title: 'Veterinary Volunteer',
      time: '2h ago'
    },
    title: "Kitten Nutrition Tip: Say No to Cow's Milk",
    content: "When feeding stray kittens under 4 weeks, avoid cow's milk as it causes severe dehydration. Use a specific Kitten Milk Replacer (KMR) and always feed them while they are on their tummies, never on their backs!",
    image: 'https://images.unsplash.com/photo-1574158622643-69d34d72650a?auto=format&fit=crop&q=80&w=600',
    likes: 856,
    commentsCount: 45,
    isLiked: false,
    isBookmarked: false,
    comments: [],
    tags: ['KittenCare', 'VetAdvice'],
    reactions: { '❤️': 35, '💡': 24, '🙌': 18 }
  },
  {
    id: 'post-3',
    author: {
      name: 'Elena Rodriguez',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150',
      title: 'Downtown Colony Caretaker',
      time: 'Today at 8:30 AM'
    },
    content: '"Breakfast is served! All 12 residents accounted for today and looking healthy."',
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=600',
    likes: 342,
    commentsCount: 18,
    isLiked: false,
    isBookmarked: false,
    comments: [],
    tags: ['CommunityFeeding', 'StrayCare'],
    reactions: { '❤️': 15, '😂': 2, '🙌': 12 }
  }
];

